name: Release package
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
          always-auth: "true"

      - uses: actions/checkout@v2

      - uses: rlespinasse/github-slug-action@v3.x

      - name: Set version
        run: npm version --new-version $(echo ${{ env.GITHUB_REF_SLUG }}|cut -c2-) --no-git-tag-version

      - name: Install dependencies
        run: npm ci

      - name: Release to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
